# 'Pythonic' loops
Many developers, especially if coming from C++, Java, JavaScript, use multi-line for loops a lot.
In python, the same operations can be done, without performance loss, in fewer lines and that are much more readable to others. 

This example takes the the task of filterig missing data values, NaN and infinite values from a numpy array.
m1 uses multi-line for loops, the other 3 use single line loops that are more common in pyhton, and more readable.

The computation time is similar.

In [1]:
import numpy as np
nodata =0
y = np.random.randint(-1,3, 100000)


def m1(y):
    # The C++, Java, JavaScript way
    m = y.shape[0]
    w = np.zeros(y.shape, dtype='float64')

    n = 0
    for ii in range(m):
        if (y[ii] == nodata) or np.isnan(y[ii]) or np.isinf(y[ii]):
            w[ii] = 0
        else:
            n += 1
            w[ii] = 1


    return w       

In [2]:
def m2(y):
    # Map, fitler, reduce functions
    w = 1 - np.fromiter(
        map(
            lambda x: ((x == nodata) or np.isnan(x) or np.isinf(x)), 
            y
        ),
        dtype='float64')
    return w

In [3]:
def m3(y):
    # List comprehension
    w = 1 - np.fromiter(
        [((x == nodata) or np.isnan(x) or np.isinf(x))
         for x in y],
        dtype='float64')

    return w

In [4]:
def m4(y):
    # Enumerate
    m = y.shape[0]
    w = np.zeros(y.shape, dtype='float64')

    for i, x in enumerate(y):
        w[i] = ((x == nodata) or np.isnan(x) or np.isinf(x))
        
    return 1 - w


In [6]:
assert (m1(y)==m2(y)).all()
assert (m1(y)==m3(y)).all()
assert (m1(y)==m4(y)).all()

In [7]:
%time m1(y)

CPU times: user 214 ms, sys: 2.99 ms, total: 217 ms
Wall time: 217 ms


array([1., 1., 1., ..., 0., 1., 1.])

In [8]:
%time m2(y)

CPU times: user 207 ms, sys: 2.81 ms, total: 210 ms
Wall time: 210 ms


array([1., 1., 1., ..., 0., 1., 1.])

In [9]:
%time m3(y)

CPU times: user 194 ms, sys: 2.74 ms, total: 196 ms
Wall time: 196 ms


array([1., 1., 1., ..., 0., 1., 1.])

In [10]:
%time m4(y)

CPU times: user 200 ms, sys: 2.58 ms, total: 203 ms
Wall time: 202 ms


array([1., 1., 1., ..., 0., 1., 1.])